# Generated by Django 4.2.3 on 2025-11-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giggle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joke",
            name="query",
            field=models.CharField(max_length=100),
        ),
    ]
