"""add_daily_jokes_table

Revision ID: 9feabdec811e
Revises: 4fc5bd88ecb9
Create Date: 2026-04-17 23:15:32.696511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9feabdec811e'
down_revision = '4fc5bd88ecb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###